sudo: false
dist: trusty
language: ruby
rvm: 2.6.5
cache: bundler
bundler_args: --retry=6
services:
  - postgresql
branches:
  only:
    - master
    - /^int-.*$/
    - /^release-.*$/
script:
  - bundle exec rake spec
before_script:
  - psql -c 'create database highlights_test;' -U postgres
before_install:
  - gem install bundler
