name: Tests

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:13
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - name: Create test database and run tests
        env:
          RAILS_ENV: test
          TEST_DB_PASS: postgres
        run: |
          cp -n config/secrets.yml.example config/secrets.yml
          bundle exec rails db:create db:schema:load db:seed --trace
          bundle exec rspec
